title = "briankidney.ca"
baseurl = "briankidney.ca"
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
builddrafts = false
canonifyurls = true
disqusShortname = "briankidney"

[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  description = "Brian Kidney"
  author = "Brian Kidney"

[permalinks]
  posts = "/:year/:month/:day/:title.html"
